//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PECOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMImages
    {
        public int ID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ImgPath { get; set; }
        public string ImgName { get; set; }
        public Nullable<int> ImgOrder { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
    }
}
